### ISSUE TITLE
wifiDirect nodes presenting problems with mobility

### ISSUE THREAD

**Issue by steucklps** [intrig-unicamp/mininet-wifi#179]
Hi
I tried to modify the example wifiDirect.py with the following mobility modifications

`net.startMobility(time=0)`                                                                                                                                                                  
`net.mobility(sta1,'start', time = 1, position='10,10,0')`                                                                                                                                              
`net.mobility(sta1,'stop', time = 29, position='30,30,0')`
`net.stopMobility(time=30)`                                                                                                              

But when this code is executed I get the following error:

Traceback (most recent call last):
  File "wifiDirect.py", line 64, in <module>
    topology()
  File "wifiDirect.py", line 38, in topology
    net.stopMobility(time=30)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.1d1-py2.7.egg/mininet/wifi/net.py", line 1836, in stopMobility
    self.auto_association()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.1d1-py2.7.egg/mininet/wifi/net.py", line 2078, in auto_association
    node.set_pos_wmediumd()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.1d1-py2.7.egg/mininet/wifi/node.py", line 504, in set_pos_wmediumd
    self.wmIface[wlan], [(float(posX)+wlan), float(posY), float(posZ)]))
AttributeError: 'Station' object has no attribute 'wmIface'

Just reporting. 
Thx

**Comment by ramonfontes** [comment]
This [commit](https://github.com/intrig-unicamp/mininet-wifi/commit/672068574f6836a2ca30a5026e529b2c25eaf9c7) solves the issue. 

Thank you.
