### ISSUE TITLE
issue running handover_bgscan.py

### ISSUE THREAD

**Issue by Suzan911** [intrig-unicamp/mininet-wifi#201]
Hi,

while I am trying to run  "handover_bgscan.py" from examples folder of mininet-wifi I got an error message:
-----------------------------------------------------------
*** Creating nodes
*** Configuring Propagation Model
*** Configuring wifi nodes
Traceback (most recent call last):
  File "handover_bgscan.py", line 71, in <module>
    topology()
  File "handover_bgscan.py", line 44, in topology
    net.configureWifiNodes()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/net.py", line 1771, in configureWifiNodes
    self.configureWmediumd()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/net.py", line 1748, in configureWmediumd
    self.stations, self.aps, self.cars, propagationModel)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/link.py", line 702, in __init__
    aps, cars, propagation_model)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/link.py", line 740, in configureWmediumd
    wmediumd.txpowers, isnodeaps, propagation_model)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/link.py", line 752, in __init__
    ppm=propagation_model)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/wmediumdConnector.py", line 392, in start
    cls.initialize(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/wmediumdConnector.py", line 534, in initialize
    preexec_fn=os.setpgrp)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

-----------------------------------------------------------
any idea about how to solve it, please ????

Thank you

**Comment by Suzan911** [comment]
when I run the (sudo util/install.sh -l) 
I got sudo: util/install.sh: command not found !

and the examples/wmediumd_interference.py not works too

Sorry but I am new to mininet-wifi, what do suggest me t do?

**Comment by ramonfontes** [comment]
You probably don't have wmediumd and you need it (`sudo util/install.sh -l` works).

**Comment by ramonfontes** [comment]
The command works!

**Comment by Suzan911** [comment]
Oh, yes it works, I was not in the mininet-wifi directory

**Comment by Suzan911** [comment]
Now the" handoff_bgscan.py" work,
Thank you so much.
