### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by LucDomingo** [intrig-unicamp/mininet-wifi#212]
Hello, I have a problem with some script in particular vanet.py and vanet-sumo.py : 
*** Creating nodes
*** Configuring Propagation Model
*** Configuring wifi nodes
Traceback (most recent call last):
  File "vanet.py", line 84, in <module>
    topology()
  File "vanet.py", line 45, in topology
    net.configureWifiNodes()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/net.py", line 1765, in configureWifiNodes
    self.configureWmediumd()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/net.py", line 1742, in configureWmediumd
    self.wmediumdMac)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/link.py", line 729, in __init__
    aps, cars, propagation_model, maclist)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/link.py", line 778, in configureWmediumd
    maclist)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/link.py", line 790, in __init__
    ppm=propagation_model, maclist=maclist)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/wmediumdConnector.py", line 220, in start
    cls.initialize(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/wmediumdConnector.py", line 362, in initialize
    preexec_fn=os.setpgrp)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Think for your time !

**Comment by ramonfontes** [comment]
Did you install **wmediumd**? It seems that **wmediumd** isn't installed.

**Comment by LucDomingo** [comment]
Thank you very much ! My problem is resolved !
