### ISSUE TITLE
AttributeError: ‘str’ object has no attribute ‘_keep_alive’ (replayingRSSI.py)

### ISSUE THREAD

**Issue by TheARP98** [intrig-unicamp/mininet-wifi#228]
Hello,

So I tried to run replayingRSSI.py, but got the error message as displayed in the title. Here's the extended message.

```
aprotyas@aprotyas-VirtualBox:~/mininet-wifi/examples/replaying$ sudo python replayingRSSI.py
*** Creating nodes
*** Configuring wifi nodes
*** Adding Link
*** Starting network
*** Configuring nodes
Traceback (most recent call last):
  File "replayingRSSI.py", line 67, in <module>
    topology()
  File "replayingRSSI.py", line 42, in topology
    replayingRSSI(net)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/replaying.py", line 222, in __init__
    mobility.thread_._keep_alive = True
AttributeError: 'str' object has no attribute '_keep_alive'
```

**Comment by ramonfontes** [comment]
`git pull` and `sudo make install` will fix the problem.

**Comment by TheARP98** [comment]
Thank you!
