### ISSUE TITLE
How to draw a line 

### ISSUE THREAD

**Issue by FT-199** [intrig-unicamp/mininet-wifi#239]
I am going to draw a line in the generated plot by mininet wifi as follows:

net.plotGraph(max_x=500, max_y=500)
net.plot.draw(rsus[0],rsus[1])

but I received the following error:

Traceback (most recent call last):
  File "my_mobility.py", line 85, in <module>
    topology(coord)
  File "my_mobility.py", line 45, in topology
    net.plot.addLine(rsus[0],rsus[1])
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4-py2.7.egg/mn_wifi/plot.py", line 346, in addLine
    cls.line(line)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4-py2.7.egg/mn_wifi/plot.py", line 201, in line
    ax.add_line(line)
AttributeError: 'NoneType' object has no attribute 'add_line'

**Comment by ramonfontes** [comment]
If you create a wired link between rsus[0] and rsus[1] a line should be plotted. However, if you want to use something like `net.plot.draw(rsus[0],rsus[1])` you need to modify the code base of Mininet-WiFi.
