### ISSUE TITLE
Telemetry errors

### ISSUE THREAD

**Issue by Diggensag** [intrig-unicamp/mininet-wifi#251]
Hi ramon, wanted to try the new sample and noticed this one:

```
root@thesitude65:/.../GITs/mininet-wifi/examples# ./socket_server.py 
*** Creating nodes
*** Configuring wifi nodes
*** Creating links
*** Starting network
*** Configuring nodes
*** Running CLI
*** Starting CLI:
mininet-wifi> /bin/sh: 1: util/m: not found
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4-py2.7.egg/mn_wifi/telemetry.py", line 84, in start
    parseData.start(nodes, fig, self.axes, single=single, data_type=data_type)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4-py2.7.egg/mn_wifi/telemetry.py", line 300, in start
    cls.phys, cls.ifaces = telemetry.get_phys(nodes, inNamespaceNodes)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4-py2.7.egg/mn_wifi/telemetry.py", line 136, in get_phys
    shell=True).split("\n")
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'util/m sta1 ls /sys/class/ieee80211/' returned non-zero exit status 127


mininet-wifi> exit
*** Stopping network
*** Stopping 0 controllers

*** Stopping 3 links
...
*** Stopping switches/access points
ap1 
*** Stopping nodes
h1 sta1 sta2 
*** Killing hostapd
*** Killing mac80211_hwsim

*** Done
```

Looking into that directory (or should i look from console from sta1?)
```
root@thesitude65# ls /sys/class/ieee80211/
phy0
```

I have a Ubuntu 18.04 LTS installation, with removed networkmanager.

**Comment by ramonfontes** [comment]
Hi,

The current implementation requires you to run the code from the mn-wifi's root directory.

**Comment by Diggensag** [comment]
Okay, then I can close this issue and add it to my personal faq :-)

**Comment by ramonfontes** [comment]
Fixed with https://github.com/intrig-unicamp/mininet-wifi/commit/3ea7e7ccd07e96b38e264e884aac7f7d7e6c9cb7 ;)

**Comment by Diggensag** [comment]
works.
