### ISSUE TITLE
new socket feature (1/2): just receiving one message

### ISSUE THREAD

**Issue by Diggensag** [intrig-unicamp/mininet-wifi#252]
Hi,

i've taken the example code and made my custom function out of it. It's still very hardcoded:

```
def getCoordinatesOverSocket(stationname):
    host = socket.gethostname()  # get local machine name
    port = 12345  # Make sure it's within the > 1024 $$ <65535 range
    s = socket.socket()
    s.connect((host, port))

    #message = raw_input('-> ')
    message = "get.sta1.position"
    #while message != 'q':
    s.send(str(message).encode('utf-8'))
    data = s.recv(1024).decode('utf-8')
    print('Received from server: ' + data)
    #message = raw_input('-> ')
    s.close()

    return data
```
running this from my machine directly it connects to the server socket, gets the coordinates but it also crashes the server. The server quits with:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4-py2.7.egg/mn_wifi/net.py", line 228, in start_socket
    c.send(str(data).encode('utf-8'))
error: [Errno 32] Broken pipe
```

**Comment by ramonfontes** [comment]
Try https://github.com/intrig-unicamp/mininet-wifi/commit/221f52dae0c7328ef14c07106d776c43dac99efa and let me know whether it works now.

**Comment by Diggensag** [comment]
Fixed so far.
