### ISSUE TITLE
Exceptions without AP/AP-link in socket_server.py

### ISSUE THREAD

**Issue by Diggensag** [intrig-unicamp/mininet-wifi#258]
Hi Ramon,
I was now refactoring my car node to the new socket feature and found that:

if I remove the AP completely from the example/socket_server.py
or for example "net.addLink(ap1, h1)" I get exceptions in the second thread.

Removed completely:
```
Traceback (most recent call last):
  File "./warmup_006_small_umbauaufSocket.py", line 339, in <module>
    topology()
  File "./warmup_006_small_umbauaufSocket.py", line 62, in topology
    net.addNAT().configDefault()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4-py2.7.egg/mn_wifi/net.py", line 419, in addNAT
    connect = self.aps[0]
IndexError: list index out of range
```

just commented out "net.addLink(ap1, h1)":
```
./socket_server.py 
*** Creating nodes
*** Configuring wifi nodes
*** Creating links
*** Starting network
*** Configuring nodes
*** defaultIntf: warning: h1 has no interfaces
*** Running CLI
*** Starting CLI:
mininet-wifi> Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4-py2.7.egg/mn_wifi/telemetry.py", line 85, in start
    parseData.start(nodes, fig, self.axes, single=single, data_type=data_type)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4-py2.7.egg/mn_wifi/telemetry.py", line 301, in start
    cls.phys, cls.ifaces = telemetry.get_phys(nodes, inNamespaceNodes)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4-py2.7.egg/mn_wifi/telemetry.py", line 144, in get_phys
    ifaces = cls.get_ifaces(nodes, inNamespaceNodes, phy_list)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4-py2.7.egg/mn_wifi/telemetry.py", line 112, in get_ifaces
    if nodes[j] not in ifaces:
IndexError: list index out of range
```

Is this AP needed for the socketConnection in any way?

**Comment by ramonfontes** [comment]
Hi,

Did you comment out `net.aps` in https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/socket_server.py#L41?

**Comment by Diggensag** [comment]
In socket_server.py ist was 
https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/socket_server.py#L34

**Comment by Diggensag** [comment]
I'll try to come up with a example for the first part also.

**Comment by ramonfontes** [comment]
The `addNAT()` function requires at least one AP or switch. Without APs or switches the system cannot add a NAT to the Mininet network.

**Comment by Diggensag** [comment]
Alright, so I could place the AP somewhere far away where it would not interfere with my experiment, but enable socket communication? -> Then I'd try it this way :-)

**Comment by ramonfontes** [comment]
Yes!
