### ISSUE TITLE
coordinate socket vs. multiple wlan interfaces

### ISSUE THREAD

**Issue by Diggensag** [intrig-unicamp/mininet-wifi#266]
So, now having the good socket_server.py I tried to integrate that, but found some other combination problems, I guess(?).

Sorry I have no example scenario ready, but here is what's happening:
Using the socket_server.py mechanics causes two different errors when using multiple wlans.

Working:
```
car1 = net.addStation('car1', position='10.0,10.0,0.0', range=mobilenoderange, speed=1)
```
like a charm.

Not working #1:
```
car1 = net.addStation('car1', position='10.0,10.0,0.0', wlans=2, range=mobilenoderange, speed=1)
```
results in:
```
*** Configuring wifi nodes
*** Connecting to wmediumd server /var/run/wmediumd.sock
Traceback (most recent call last):
  File "./automatic_szenario.py", line 431, in <module>
    topology(streetlightdict, streetlightrange, outtakerate, szenarioname, currentCarTrack, mobilenoderange, edgeboxsetuptime, edgeboxsize, algoname, runnumber, alpha)
  File "./automatic_szenario.py", line 263, in topology
    net.configureWifiNodes()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4.1-py2.7.egg/mn_wifi/net.py", line 1717, in configureWifiNodes
    if int(node.params['range'][wlan]) == 0:
IndexError: list index out of range
```
causing mn-wifi to halt.

Not working #2: 
```
car1 = net.addStation('car1', position='10.0,10.0,0.0', wlans=2)
```
which results in:
```
*** Starting CLI:
mininet-wifi> Exception in thread replayingMobility:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4.1-py2.7.egg/mn_wifi/replaying.py", line 84, in mobility
    calc_pos(node, time_)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4.1-py2.7.egg/mn_wifi/replaying.py", line 40, in notimestamp_
    for n in range(0, node.params['speed']):
TypeError: range() integer end argument expected, got float.


mininet-wifi> car1 python2 /home/.../getgeocoords.py
Traceback (most recent call last):
  File "/home/.../getgeocoords.py", line 22, in <module>
    client()
  File "/home/.../getgeocoords.py", line 7, in client
    s.connect((host, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 113] No route to host
mininet-wifi> exit
*** Stopping network
*** Stopping 0 controllers

*** Stopping 20 links
....................
*** Stopping switches/access points
ap1 
*** Stopping nodes
h1 nat0 sta1 sta2 sta1 sta2 sta3 sta4 sta5 sta6 sta7 sta8 sta9 sta10 sta11 sta12 sta13 sta14 car1 

*** Removing WiFi module and Configurations

*** Done
```
But CLI is still usable. Hence still no connection.

I found this, because I was trying to add a second interface to my car. I need its wlan0 to be in adhoc mode to connect to the other nodes, therefore I thought I could add a second interface, which I then leave connected to the AP that has the natting connection to the host.

I will try a workaround in the meantime, like just pushing the coordinates via "echo xyz >> coordfile".

**Comment by ramonfontes** [comment]
I unsuccessfully tried to reproduce the same behaviour. Can you try a `git pull` and `sudo make install`?
