### ISSUE TITLE
Error - CMD net in wifiDirect.py example 

### ISSUE THREAD

**Issue by davidcawork** [intrig-unicamp/mininet-wifi#296]
Hi!

I left the execution trace below. It would be a good idea to encapsulate the Mininet-Wifi CLI commands in try-except blocks so that they can handle these errors and not be thrown out of the CLI. 

Thank you,

---

```bash
n0obie@n0obie-VirtualBox:~/mininet-wifi/examples$ sudo python wifiDirect.py
*** Creating nodes
*** Configuring Propagation Model
*** Configuring wifi nodes
*** Starting WiFi Direct
*** Starting network
*** Connecting to wmediumd server /var/run/wmediumd.sock
*** Configuring nodes
*** Running CLI
*** Starting CLI:
mininet-wifi> net
sta1 sta1-wlan0:Traceback (most recent call last):
  File "wifiDirect.py", line 62, in <module>
    topology(sys.argv)
  File "wifiDirect.py", line 54, in topology
    CLI(net)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4.3-py2.7.egg/mn_wifi/cli.py", line 12, in __init__
    MN_CLI.__init__(self, mn_wifi, stdin=sys.stdin, script=None)
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 70, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 105, in run
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 161, in do_net
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 328, in dumpNodeConnections
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 319, in dumpConnections
AttributeError: 'WifiDirectLink' object has no attribute 'link'
n0obie@n0obie-VirtualBox:~/mininet-wifi/examples$

```

**Comment by ramonfontes** [comment]
Fixed with https://github.com/intrig-unicamp/mininet-wifi/commit/43cfbfa391e9fd2740590ad6403c2208e04677fb
