### ISSUE TITLE
vanet-sumo.py error

### ISSUE THREAD

**Issue by ntefengm** [intrig-unicamp/mininet-wifi#300]
Hi,

May I please get assistance on this error. vanet-sumo.py gives the following error :

*** Creating nodes
*** Configuring Propagation Model
*** Configuring wifi nodes
Traceback (most recent call last):
  File "vanet-sumo.py", line 99, in <module>
    topology()
  File "vanet-sumo.py", line 54, in topology
    net.configureWifiNodes()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.5-py2.7.egg/mn_wifi/net.py", line 1297, in configureWifiNodes
    self.configNodes()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.5-py2.7.egg/mn_wifi/net.py", line 1123, in configNodes
    managed(node, wlan)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.5-py2.7.egg/mn_wifi/link.py", line 909, in __init__
    value = node.params[key][wlan].split(',')
IndexError: list index out of range

**Comment by ramonfontes** [comment]
https://github.com/intrig-unicamp/mininet-wifi/commit/f19e46f95283eb7b0d9ed51feaf401a161137c32 fixes the issue.
