### ISSUE TITLE
Issue using wmediumd

### ISSUE THREAD

**Issue by masad8** [intrig-unicamp/mininet-wifi#335]
Hi,

I am using Mininet-WiFi using Python API. Everything sees to be working fine except the wmediumd. I have installed wmediumd along with Mininet-WiFi installation, however, when I use wmediumd in Pythons script, I get the following error:

```
Connecting to wmediumd server /var/run/wmediumd.sock
Traceback (most recent call last):
  File "miniwifitest.py", line 64, in <module>
    topology(sys.argv)
  File "miniwifitest.py", line 33, in topology
    net.configureWifiNodes()
  File "/home/mininet-wifi/mn_wifi/net.py", line 1318, in configureWifiNodes
    self.start_wmediumd()
  File "/home/mininet-wifi/mn_wifi/net.py", line 1229, in start_wmediumd
    aps=self.aps, cars=self.cars, ppm=ppm)
  File "/home/mininet-wifi/mn_wifi/link.py", line 1396, in __init__
    self.configWmediumd(**kwargs)
  File "/home/mininet-wifi/mn_wifi/link.py", line 1432, in configWmediumd
    isnodeaps=isnodeaps, ppm=ppm)
  File "/home/mininet-wifi/mn_wifi/wmediumdConnector.py", line 175, in __init__
    self.start(**kwargs)
  File "/home/mininet-wifi/mn_wifi/wmediumdConnector.py", line 191, in start
    w_server.connect()
  File "/home/mininet-wifi/mn_wifi/wmediumdConnector.py", line 662, in connect
    cls.sock.connect(uds_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory
```

Can you please tell what could be the issue?

**Comment by ramonfontes** [comment]
AFAIK, the message `socket.error: [Errno 2] No such file or directory` means that either you haven't installed wmediumd or you are using other wmediumd version than that one provided by util/install.sh -l.

**Comment by masad8** [comment]
I am using Python 2.7, and also I installed mininet-wifi using `sudo util/install.sh -Wlnfv`. This should probably the correct version of wmediumd?

**Comment by ramonfontes** [comment]
Wmediumd is written in C. So the python version won't be a problem. `sudo util/install.sh -Wlnfv` installs the correct version. I suggest you to make sure that your system has installed wmediumd correctly. In other words, that no error was encountered during its installation.

**Comment by ramonfontes** [comment]
Closing due to inactivity
