### ISSUE TITLE
AttributeError: 'master' object has no attribute 'wmIface'

### ISSUE THREAD

**Issue by CITIZENDOT** [intrig-unicamp/mininet-wifi#488]
Here's my topology: https://gist.github.com/CITIZENDOT/f4df62da940a26baaaf1fa0668ebea1b (generated by miniedit)

Error log
```
Traceback (most recent call last):
  File "./topo.py", line 69, in <module>
    myNetwork()
  File "./topo.py", line 41, in myNetwork
    net.configureWifiNodes()
  File "/usr/local/lib/python3.8/dist-packages/mininet_wifi-2.6-py3.8.egg/mn_wifi/net.py", line 1363, in configureWifiNodes
    self.start_wmediumd()
  File "/usr/local/lib/python3.8/dist-packages/mininet_wifi-2.6-py3.8.egg/mn_wifi/net.py", line 1261, in start_wmediumd
    wmediumd(wlinks=self.wlinks, fading_cof=self.fading_cof,
  File "/usr/local/lib/python3.8/dist-packages/mininet_wifi-2.6-py3.8.egg/mn_wifi/link.py", line 1501, in __init__
    self.configWmediumd(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mininet_wifi-2.6-py3.8.egg/mn_wifi/link.py", line 1541, in configWmediumd
    self.interference(nodes)
  File "/usr/local/lib/python3.8/dist-packages/mininet_wifi-2.6-py3.8.egg/mn_wifi/link.py", line 1566, in interference
    self.positions.append(w_pos(intf.wmIface, [posX, posY, posZ]))
AttributeError: 'master' object has no attribute 'wmIface'
```

**Comment by ramonfontes** [comment]
Two aps named `ap1`? This is no a desirable scenario for programming languages. :(
