### ISSUE TITLE
AttributeError: 'LowPANNode' object has no attribute 'position'

### ISSUE THREAD

**Issue by EvertonZanotelli** [intrig-unicamp/mininet-wifi#491]
I'm using the VM version o mininet-wifi updated

wifi@wifi-virtualbox:~/mininet-wifi/examples$ sudo python 6LoWPan.py 
[sudo] password for wifi: 
*** Creating nodes
*** Configuring nodes
*** Adding links
*** Starting network
*** Running CLI
*** Starting CLI:
mininet-wifi> distance sensor1 sensor2
Traceback (most recent call last):
  File "6LoWPan.py", line 65, in <module>
    topology()
  File "6LoWPan.py", line 57, in topology
    CLI(net)
  File "/usr/local/lib/python3.8/dist-packages/mininet_wifi-2.6-py3.8.egg/mn_wifi/cli.py", line 21, in __init__
    MN_CLI.__init__(self, mn_wifi, stdin=stdin, script=script)
  File "/usr/local/lib/python3.8/dist-packages/mininet/cli.py", line 70, in __init__
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/mininet/cli.py", line 114, in run
    self.cmdloop()
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.8/dist-packages/mininet_wifi-2.6-py3.8.egg/mn_wifi/cli.py", line 45, in do_distance
    self.mn.get_distance(*args)
  File "/usr/local/lib/python3.8/dist-packages/mininet_wifi-2.6-py3.8.egg/mn_wifi/net.py", line 1065, in get_distance
    dist = src.get_distance_to(dst)
  File "/usr/local/lib/python3.8/dist-packages/mininet_wifi-2.6-py3.8.egg/mn_wifi/node.py", line 291, in get_distance_to
    pos_src = self.position
AttributeError: 'LowPANNode' object has no attribute 'position'

**Comment by ramonfontes** [comment]
Closing due to no new interactions.
