### ISSUE TITLE
iperf error in Ubuntu 20.04

### ISSUE THREAD

**Issue by zaheenSyed** [intrig-unicamp/mininet-wifi#534]
I have been trying to run iperf from mininet-wifi but I am always getting this error. 

Here is the whole error:

"zemsyed@ZET:~/mininet-wifi$ sudo python3 ./examples/telemetry.py 
/usr/local/lib/python3.8/dist-packages/matplotlib/backends/backend_gtk3agg.py:15: UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try installing cairocffi.
  warnings.warn(
*** Creating nodes
*** Configuring Propagation Model
*** Configuring nodes
*** Connecting to wmediumd server /var/run/wmediumd.sock
*** Starting network
*** Running CLI
*** Starting CLI:
mininet-wifi> iperf
*** Iperf: testing TCP bandwidth between sta1 and sta3 
Traceback (most recent call last):
  File "./examples/telemetry.py", line 53, in <module>
    topology()
  File "./examples/telemetry.py", line 45, in topology
    CLI(net)
  File "/usr/local/lib/python3.8/dist-packages/mininet_wifi-2.6-py3.8.egg/mn_wifi/cli.py", line 21, in __init__
    MN_CLI.__init__(self, mn_wifi, stdin=stdin, script=script)
  File "/usr/local/lib/python3.8/dist-packages/mininet/cli.py", line 70, in __init__
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/mininet/cli.py", line 114, in run
    self.cmdloop()
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.8/dist-packages/mininet/cli.py", line 230, in do_iperf
    self.mn.iperf()
  File "/usr/local/lib/python3.8/dist-packages/mininet_wifi-2.6-py3.8.egg/mn_wifi/net.py", line 1046, in iperf
    result = [self._parseIperf(servout), self._parseIperf(cliout)]
**AttributeError: 'Mininet_wifi' object has no attribute '_parseIperf'**
zemsyed@ZET:~/mininet-wifi$ "

**Comment by ramonfontes** [comment]
Please use iperf with xterm via `makeTerm`
